#! /bin/bash

# Defaults
IN_PORTNUMBER_KCP=${PORTNUMBER_KCP:-9534}
IN_PORTNUMBER_NOKCP=${PORTNUMBER_NOKCP:-9533}
IN_BINDADDR=${BINDADDR:-0.0.0.0}
IN_LOCALPORT=${LOCALPORT:-997}
IN_LOCALHOST=${LOCALHOST:-127.0.0.1}
IN_MTU_KCP=${MTU_KCP:-1200}
IN_MODE_KCP=${MODE_KCP:-fast}
IN_DSCP_KCP=${DSCP_KCP:-46}
IN_ENCRYPTION_KCP=${ENCRYPTION_KCP:-none}
IN_ENCRYPTION_SS=${ENCRYPTION_SS:-aes-256-gcm}
IN_OBFS_METHOD=${OBFS_METHOD:-tls}

# Bin
SHADOWSOCKS="/usr/local/bin/ss-server"
KCPTUN="/usr/go/bin/server"

# Formatting
bold=$(tput bold)
normal=$(tput sgr0)
red='\033[0;31m'
blue='\033[0;34m'

# Sanity checks
if [ -z "$PASSWORD_SS" ]
then
      echo -e "${bold}${red}Error: No Shadowsocks password set. Set \$PASSWORD_SS"${normal}
      exit 1
fi
if [ -z "$PASSWORD_KCP" ]
then
      echo -e "${bold}${red}Error: No KCP password set. Set \$PASSWORD_KCP"${normal}
      exit 1
fi

if [[ ( $IN_ENCRYPTION_SS != *"gcm" ) && ( $IN_ENCRYPTION_SS != *"poly1305" ) ]]
then
      echo -e "${bold}${red}Warning : Selected encryption method ($IN_ENCRYPTION_SS) does not implement AEAD ciphers. AEAD ciphers should always be prefered.${normal}"
fi

echo "[Launching obfuscated Shadowsocks server over KCP tunnel...]"
echo -e "[\$BINDADDR:\$PORTNUMBER_KCP]    KCP endpoint:            ${bold}${blue}$IN_BINDADDR${normal}:${bold}${blue}$IN_PORTNUMBER_KCP"${normal}
echo -e "[\$MODE_KCP]                    KCP tunel mode:          ${bold}${blue}$IN_MODE_KCP"${normal}
echo -e "[\$DSCP_KCP]                    KCP tunel DSCP:          ${bold}${blue}$IN_DSCP_KCP"${normal}
echo -e "[\$ENCRYPTION_KCP]              KCP tunel encryption:    ${bold}${blue}$IN_ENCRYPTION_KCP"${normal}
echo -e "[\$ENCRYPTION_SS]               Shadowsocks encryption:  ${bold}${blue}$IN_ENCRYPTION_SS"${normal}
echo -e "[\$OBFS_METHOD]                 OBFS method:             ${bold}${blue}$IN_OBFS_METHOD"${normal}
echo ""

$KCPTUN -l :$PORTNUMBER_KCP -t $IN_LOCALHOST:$IN_LOCALPORT --crypt $IN_ENCRYPTION_KCP --mtu $IN_MTU_KCP --nocomp --mode $IN_MODE_KCP --dscp $IN_DSCP_KCP --key $PASSWORD_KCP &
$SHADOWSOCKS -s $IN_BINDADDR -p $IN_LOCALPORT -k $PASSWORD_SS -m $IN_ENCRYPTION_SS -u --plugin obfs-server --plugin-opts "obfs=$IN_OBFS_METHOD" --fast-open &

echo "[Launching obfuscated Shadowsocks server whith no tunneling...]"
echo -e "[\$BINDADDR:\$PORTNUMBER_NOKCP]  Shadowsocks endpoint:    ${bold}${blue}$IN_BINDADDR${normal}:${bold}${blue}$IN_PORTNUMBER_NOKCP"${normal}
echo -e "[\$ENCRYPTION_SS]               Shadowsocks encryption:  ${bold}${blue}$IN_ENCRYPTION_SS"${normal}
echo -e "[\$OBFS_METHOD]                 OBFS method:             ${bold}${blue}$IN_OBFS_METHOD"${normal}
echo ""

$SHADOWSOCKS -s $IN_BINDADDR -p $IN_PORTNUMBER_NOKCP -k $PASSWORD_SS -m $IN_ENCRYPTION_SS -u --plugin obfs-server --plugin-opts "obfs=$IN_OBFS_METHOD" --fast-open